name: uShop
depends: [Vault]
soft-depends: [Essentials, EvenMoreFish]
author: Linus122
main: xyz.spaceio.ushop.Main
version: 2.3.3-SNAPSHOT
api-version: 1.21.5
description: easy sell your stuff
commands:
   ushop:
      description: main command of ushop
      usage: /<command>
      permission: ushop.admin